### ISSUE TITLE
Capture gecko log

### ISSUE THREAD

**Issue by EricRahm** [mozilla/areweslimyet#52]
Particularly for custom runs it would be useful to be able to get the gecko log. For m-i builds it's probably less important and would take up a ton of disk space.

**Comment by sethfowler** [comment]
[MemShrink: P1] =)

**Comment by jetvillegas** [comment]
For the short term, can we ssh in to get the logs from the last runs?

**Comment by sethfowler** [comment]
Having access to the logs (current and future) from the "bug1122704" series will help a lot. Not sure if there's another way to do that before we get this feature in the UI.

**Comment by EricRahm** [comment]
Currently there are no logs stored on the server. We can certainly make this a 2 step process:
- First start storing the gecko log for custom runs
- Expose those somehow

I think this needs to come after switching to marionette in #55

**Comment by EricRahm** [comment]
c567bbe4f769bdea816ce289a76c54ef211d5d5e in PR #57 should take care of part 1.

**Comment by EricRahm** [comment]
I'm going to call this good enough. Now that we have the marionette version running gecko logs for each run are captured on the server. You'll still have to bug someone with access to the server for the logs but at least they're there.

@sethfowler If you think it's particularly important to have *easy* access to the logs can you file another issue?
