### ISSUE TITLE
Rework database to include process info

### ISSUE THREAD

**Issue by EricRahm** [mozilla/areweslimyet#77]
We need to include a process name when adding values to the database and update the the json generation to handle the presence of a process name.

One option is to just shove it in as an additional `:metedata` field. Preferably we'd add a process name column / table to the DB instead. This might be a good time to split out other metadata fields and add the heap kind from #39 in.

**Comment by Nephyrin** [comment]
The only thing to be careful of here is old databases -- if we ever want to graph a new line from the existing data, we can add it to `create_graph_json.py` and nuke the old json, which doesn't work if the database format changes.

I'd been working around this by keeping `util/update_database.py` aware of all old formats and able to do any -> newest conversion, so if we ever want to re-export an old database, we can just run update on it after unarchive.

**Comment by EricRahm** [comment]
This is being worked on in #80, I went with the updating the DB schema.

**Comment by EricRahm** [comment]
Landed on the e10s branch in ae88a34fc359c29e51a9231b4ccb54951bdbb0ea
