### ISSUE TITLE
Handle process names in the json creation script

### ISSUE THREAD

**Issue by EricRahm** [mozilla/areweslimyet#78]
Once process names are added to the DB (#77) we should update our scripts to actually use them.

**Comment by Nephyrin** [comment]
`create_graph_json.py` handles existing metadata by adding it to the datapoint, e.g.

| Meta                                  | Datapoint        |
| --------------------------------: | -----------------: |
| Iteration 1:CheckpointFoo | blah/explicit/js |

becomes `Iteration 1/CheckpointFoo/blah/explicit/js`

The reason these fields aren't just baked into the datapoint by the test to begin with is the silly string de-duplication stuff. We don't want to store each reporter name `iterations * checkpoints` times per run in sqlite. A database with proper transparent compression would solve this, so we could just prefix whatever onto the reporter name and it would work.

Also, the website is hardcoded to mark certain 'depths' of the tree as special in a few spots, but these are easy to increment if we add another level for process:
https://github.com/mozilla/areweslimyet/blob/master/html/slimyet.js#L820
https://github.com/mozilla/areweslimyet/blob/master/html/slimyet.js#L821
https://github.com/mozilla/areweslimyet/blob/master/html/slimyet.js#L928

**Comment by Nephyrin** [comment]
For the record, if you change the JSON format, the procedure to re-export the old databases is roughly:

    # Run this over a weekend, it wont be quick, these DBs are huge and sqlite slow
    for compressedMonthDB in db/areweslimyet-*.sqlite.xz; do
      monthDB="${compressedMonthDB%.xz}"
      seriesName="$(basename "${monthDB%.sqlite}")"
      monthJSON="html/data/$seriesName.json.gz"
      util/unarchive_db.sh "$compressedMonthDB"
      util/update_db.py "$monthDB"
      mv -v "$monthJSON" "$monthJSON.oldFormat"
      ./create_graph_json.py "$monthDB" "$seriesName" html/data/
      util/archive_db.sh "$monthDB"
    done

(do this one at a time with a script because having them all uncompressed at once will fill the disk)

**Comment by EricRahm** [comment]
As of ae88a34fc359c29e51a9231b4ccb54951bdbb0ea `create_graph_json.py` handles the new DB format but doesn't actually use anything but the main process. The next step is to update the script to use the process names (and annotate kinds).

**Comment by EricRahm** [comment]
This landed in a11f3ec4b069377a7a036706b05eb54cb611aaf1 on the e10s branch.
